/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SplitRouteImport } from './routes/split'
import { Route as SignRouteImport } from './routes/sign'
import { Route as PdfToImagesRouteImport } from './routes/pdf-to-images'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as EncryptRouteImport } from './routes/encrypt'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as IndexRouteImport } from './routes/index'

const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImagesRoute = PdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptRoute = EncryptRouteImport.update({
  id: '/encrypt',
  path: '/encrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/encrypt': typeof EncryptRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/encrypt': typeof EncryptRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/encrypt': typeof EncryptRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/encrypt'
    | '/image-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/encrypt'
    | '/image-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/encrypt'
    | '/image-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  EncryptRoute: typeof EncryptRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  MergeRoute: typeof MergeRoute
  MetadataRoute: typeof MetadataRoute
  OcrRoute: typeof OcrRoute
  OrganizeRoute: typeof OrganizeRoute
  PageNumbersRoute: typeof PageNumbersRoute
  PdfToImagesRoute: typeof PdfToImagesRoute
  SignRoute: typeof SignRoute
  SplitRoute: typeof SplitRoute
  UnlockRoute: typeof UnlockRoute
  WatermarkRoute: typeof WatermarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-images': {
      id: '/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/pdf-to-images'
      preLoaderRoute: typeof PdfToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypt': {
      id: '/encrypt'
      path: '/encrypt'
      fullPath: '/encrypt'
      preLoaderRoute: typeof EncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  EncryptRoute: EncryptRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  MergeRoute: MergeRoute,
  MetadataRoute: MetadataRoute,
  OcrRoute: OcrRoute,
  OrganizeRoute: OrganizeRoute,
  PageNumbersRoute: PageNumbersRoute,
  PdfToImagesRoute: PdfToImagesRoute,
  SignRoute: SignRoute,
  SplitRoute: SplitRoute,
  UnlockRoute: UnlockRoute,
  WatermarkRoute: WatermarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
